export const BOOKINGS_SERVER_CONSTANTS = {
	MONGODB: {
		URI: process.env.MONGODB_URI!,
	},
	CASHFREE: {
		CASHFREE_API_VERSION: process.env.CASHFREE_API_VERSION!,
		CASHFREE_CLIENT_ID: process.env.CASHFREE_CLIENT_ID!,
		CASHFREE_CLIENT_SECRET: process.env.CASHFREE_CLIENT_SECRET!,
		CASHFREE_SECURE_CLIENT_ID: process.env.CASHFREE_SECURE_CLIENT_ID!,
		CASHFREE_SECURE_CLIENT_SECRET: process.env.CASHFREE_SECURE_CLIENT_SECRET!,
	},
};
